### ISSUE TITLE
[documentation] How use funnels with this package ?

### ISSUE THREAD

**Issue by stoto34** [maxandriani/ngx-hotjar#16]
Hi,

I defined a funnel on Hotjar but it seems it doesn't work, I haven't any session (tried with contains, start with or simple match). What do I need to do to see session on Hotjar ? Should I use the Hotjar service and  tag ?

Thank you for your help

**Comment by maxandriani** [comment]
@stoto34 I did some tests and I was unnable to simulate your issue. I'll appreciate if you could try some test cases as follow described:

## Checks

- [ ] Check if your app has ngx-hotjar plugin working properly. To do that you can use the "Verify Instalation" button on Hotjar dashboard. Or you can even call you local environment w/ `?hjVerifyInstall=>>siteId<<` query param.

  ![Anotação 2020-06-22 093242](https://user-images.githubusercontent.com/7096439/85288398-0c0f0500-b46c-11ea-8e69-b511d6238e06.png)

- [ ] Than, if you want to use our `NgxHotjarRouterModule` to listen RouterModule and perform page view calls. Please, check if `NgxHotjarRouterModule` is on same level at `NgxHotjarModule` and `Router.forRoot()` call. 

  ![Anotação 2020-06-22 093405](https://user-images.githubusercontent.com/7096439/85288400-0c0f0500-b46c-11ea-8b8f-b78ddb6c260a.png)

  If the plugin is properly installed and configured, you can check the hotjar calls on Browser's Developer Tools Window.

  ![Anotação 2020-06-22 093143](https://user-images.githubusercontent.com/7096439/85288396-0addd800-b46c-11ea-99b9-17d66ec16d3b.png)

## Help

The default configuration will only track page views changes and trigger api calls. If you have a complex funnel when you want to test user's step by step progress behaviour in a form interaction (or other kind of UX interaction), you could use the `NgxHotjarService.virtualPageView('/virtual/path');`

On the Hotjar Dashboard, you can use any kind of math strategy, but have in mind that `simple math`, `starts`, and `exact math` are kind of stricts strategies. You shall match all characters and sometimes characted case like upper and lower case.

I always prefer to perform my funnels w/ `contains` and `regex` match strategy because it is more easy to configure w/ small slug of uri. I.E.

  `https://www.maxandriani.art.br/projeto/simulador-cfc/`
  `\/projeto\/(?:[\w\-\_\d]+).*`

## Docs

`NgxHotjarService.virtualPageView()` will perform a fake uri change that you can capture as Hotjat Events.

`NgxHotjarService.stateChange()` will perform a full uri change, like a navigation event.

**Comment by stoto34** [comment]
Actually, it wasn't an issue, it takes just few hours before seing funnels stats.

Thank you by the way for your quick feedback, I have all I need
